### ISSUE TITLE
question: why gitignore `composer.lock`?

### ISSUE THREAD

**Issue by montchr** [szepeviktor/composer-managed-wordpress#28]
I noticed that you have `/composer.lock` in `.gitignore`.  Could you help me understand your reasoning and some idea of your workflow re: `composer.lock`?  Does that file not sit around as "state" that might differ across environments?

**Comment by szepeviktor** [comment]
Hello Chris! 👋🏻 
Thank you for your question.

My repositories are not "download&use" but "learn&understand".
Ignoring the lock file allows me to issue `composer update` in this template repo without introducing file changes.

![image](https://github.com/szepeviktor/composer-managed-wordpress/assets/952007/099fd689-3639-47c2-b531-eb65c29ad841)

In production you could go
1. lazy: always update all plugins - not committing the lock file
2. strict: have a lock file in the repo

**Comment by szepeviktor** [comment]
a sneak peek into the README

![image](https://github.com/szepeviktor/composer-managed-wordpress/assets/952007/714fb2df-9acc-48d1-b00e-e379ee4210b9)

**Comment by szepeviktor** [comment]
lines from the deploy script

https://github.com/szepeviktor/composer-managed-wordpress/blob/9747a8bbdde5cc727504b2cba670b36525af7901/deploy-receiver.sh#L164-L166

**Comment by montchr** [comment]
Gotcha, makes sense. Thanks for the clarification!

**Comment by szepeviktor** [comment]
Glad to talk to you.
